version: '3.3'

services:
    
    mongodb:          # service의 이름입니다.
        image: mongo    # 해당 service에서 사용할 image입니다.
        restart: always # container를 실행할 때 항상 이미 수행중이라면 재시작을 수행합니다.
        environment:    # 환경변수를 정의합니다.
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
        container_name: "mongodb" # container의 name을 정의합니다.
        ports:                # service port를 정의합니다.
        - "27017"     # local:container

    spring-server:
        #image: wbjeon2k/image_milestone4
        container_name: "spring-server"
        #restart: always
        build:
            context: . 
            dockerfile: Dockerfile
        
        links:
            - mongodb
        depends_on: 
            - mongodb
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        #
        #
        #ports:
            #- "8080:8080"