name: Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Create dummy TWwW.war
      run: touch TWwW.war
    -
      name: Build docker image
      run: docker build -t test-image ${{ github.workspace }}
    -
      name: Run docker container
      run: docker run -d --rm --name test -v ${{ github.workspace }}:/root/project/CSE364 test-image
    -
      name: Run tests
      run: |
        docker exec test bash -c 'cd /root/project/ && cp ./CSE364/mongod_install.sh ./'
        docker exec test bash -c 'cd /root/project/ && sed -i 's/\r$//' ./mongod_install.sh'
        docker exec test bash -c 'cd /root/project/ && chmod a+x ./mongod_install.sh'
        docker exec test bash -c 'cd /root/project/ && ./mongod_install.sh'
        docker exec test bash -c 'mongod &'
        docker exec test bash -c 'cd /root/project/CSE364/ && mvn clean test'
    -
      name: Kill docker container
      run: docker kill test
